export const DEVICE_ID_HEADER_NAME = 'X-GCS-ALG-DEVICE-ID';
export const DEVICE_INFO_HEADER_NAME = 'X-GCS-ALG-DEVICE-INF';

export default {
    DEVICE_ID_HEADER_NAME: DEVICE_ID_HEADER_NAME,
    DEVICE_INFO_HEADER_NAME: DEVICE_INFO_HEADER_NAME
}
